namespace: obssys
image:
  repository: ts-dockerhub.lsst.org/scheduler
  tag: c0030
  pullPolicy: Always
  nexus3: nexus3-docker
env:
  LSST_DDS_PARTITION_PREFIX: base
  LSST_SITE: base
  INDEX: 1
  OSPL_INFOFILE: /tmp/ospl-info-mtscheduler.log
  OSPL_ERRORFILE: /tmp/ospl-error-mtscheduler.log
shmemDir: /run/ospl
osplVersion: V6.10.4
