namespace: rubintv-ts8
fullnameOverride: u
image:
  repository: lsstts/rubintv-broadcaster
  tag: c0028_usdf
  pullPolicy: Always
env:
  DAF_BUTLER_REPOSITORY_INDEX: /project/data-repos.yaml
  http_proxy: http://sdfproxy.sdf.slac.stanford.edu:3128
  https_proxy: http://sdfproxy.sdf.slac.stanford.edu:3128
  squid_proxy: http://sdfproxy.sdf.slac.stanford.edu:3128
  no_proxy: .slac.stanford.edu
  HTTP_PROXY: http://sdfproxy.sdf.slac.stanford.edu:3128
  HTTPS_PROXY: http://sdfproxy.sdf.slac.stanford.edu:3128
  SQUID_PROXY: http://sdfproxy.sdf.slac.stanford.edu:3128
  NO_PROXY: .slac.stanford.edu
  DEPLOY_BRANCH: deploy-slac
  S3_ENDPOINT_URL: https://s3dfrgw.slac.stanford.edu
scripts:
- runMisc.py
- slac/ts8/runButlerWatcher.py
- slac/ts8/runIsrRunner_018.py
- slac/ts8/runIsrRunner_019.py
- slac/ts8/runIsrRunner_020.py
- slac/ts8/runIsrRunner_021.py
- slac/ts8/runIsrRunner_022.py
- slac/ts8/runIsrRunner_023.py
- slac/ts8/runIsrRunner_024.py
- slac/ts8/runIsrRunner_025.py
- slac/ts8/runIsrRunner_026.py
- slac/ts8/runMetadataServer.py
- slac/ts8/runPlotter.py
credentialFile: google_write_creds
vaultPrefixPath: secret/rubin/usdf-rubintv-broadcaster-cleanroom
pullSecretsPath: ts/software/nexus3-docker
rubinTvSecretsPath: ts/software/rubintv
credentialSecretsPath: rubintv-broadcaster
butlerSecret:
  key: butler-secret
  containerPath: /secrets
  dbUser: rubin
envSecrets:
- name: ASTROMETRY_NET_API_KEY
  secretName: rubintv
  secretKey: astrometry-net-api-key
imagePullSecrets:
- name: rubintv-broadcaster-pull-secret
pvcMountpoint:
- name: sdf-data-rubin
  containerPath: /repo
  subPath: repo
pvcMountpointClaim:
- name: sdf-group-rubin
  containerPath: /sdf/group/rubin
  claimSize: 1Gi
  accessMode: ReadWriteMany
- name: sdf-scratch
  containerPath: /scratch
  claimSize: 1Gi
  accessMode: ReadWriteMany
- name: fs-ddn-sdf-group-rubin
  containerPath: /fs/ddn/sdf/group/rubin
  claimSize: 1Gi
  accessMode: ReadWriteMany
- name: fs-ddn-sdf-group-lsst
  containerPath: /fs/ddn/sdf/group/lsst
  claimSize: 1Gi
  accessMode: ReadWriteMany
securityContext:
  uid: 15517
  gid: 4085
  fid: 4085
