image:
  repository: ts-dockerhub.lsst.org/rubintv-broadcaster
  tag: c0030
  pullPolicy: Always
env:
  DAF_BUTLER_REPOSITORY_INDEX: /project/data-repos.yaml
scripts:
- summit/auxTel/runBackgroundService.py
- summit/auxTel/runButlerWatcher.py
- summit/auxTel/runCalibrateCcdRunner.py
- summit/auxTel/runImExaminer.py
- summit/auxTel/runIsrRunner.py
- summit/auxTel/runMetadataCreator.py
- summit/auxTel/runMetadataServer.py
- summit/auxTel/runMonitor.py
- summit/auxTel/runMountTorquePlotter.py
- summit/auxTel/runNightReporter.py
- summit/auxTel/runSpecExaminer.py
- summit/comCam/runButlerWatcher.py
- summit/comCam/runIsrRunner_000.py
- summit/comCam/runIsrRunner_001.py
- summit/comCam/runIsrRunner_002.py
- summit/comCam/runIsrRunner_003.py
- summit/comCam/runIsrRunner_004.py
- summit/comCam/runIsrRunner_005.py
- summit/comCam/runIsrRunner_006.py
- summit/comCam/runIsrRunner_007.py
- summit/comCam/runIsrRunner_008.py
- summit/comCam/runMetadataServer.py
- summit/comCam/runPlotter.py
- summit/misc/runAllSky.py
- summit/misc/runMisc.py
- summit/misc/runMisc2.py
- summit/misc/runStarTracker.py
- summit/misc/runStarTrackerCatchup.py
- summit/misc/runStarTrackerFast.py
- summit/misc/runStarTrackerMetadata.py
- summit/misc/runStarTrackerNightReport.py
- summit/misc/runStarTrackerWide.py
credentialFile: google_write_creds
vaultPrefixPath: secret/k8s_operator/summit-lsp.lsst.codes
pullSecretsPath: pull-secret
rubinTvSecretsPath: ts/software/rubintv
credentialSecretsPath: rubintv-broadcaster
butlerSecret:
  key: butler-secret
  containerPath: /home/saluser/.lsst
  dbUser: oods
envSecrets:
- name: ASTROMETRY_NET_API_KEY
  secretName: rubintv
  secretKey: astrometry-net-api-key
imagePullSecrets:
- name: rubintv-broadcaster-pull-secret
nfsMountpoint:
- name: auxtel-gen3-data
  containerPath: /repo/LATISS
  readOnly: false
  server: auxtel-archiver.cp.lsst.org
  serverPath: /repo/LATISS
- name: comcam-gen3-data
  containerPath: /repo/LSSTComCam
  readOnly: false
  server: comcam-archiver.cp.lsst.org
  serverPath: /repo/LSSTComCam
- name: auxtel-data
  containerPath: /readonly/lsstdata/auxtel
  readOnly: true
  server: auxtel-archiver.cp.lsst.org
  serverPath: /lsstdata
- name: comcam-data
  containerPath: /readonly/lsstdata/comcam
  readOnly: true
  server: comcam-archiver.cp.lsst.org
  serverPath: /lsstdata
- name: project-shared
  containerPath: /project
  readOnly: false
  server: nfs1.cp.lsst.org
  serverPath: /project
- name: auxtel-gen3-data-temp
  containerPath: /data/lsstdata/base/auxtel
  readOnly: true
  server: auxtel-archiver.cp.lsst.org
  serverPath: /lsstdata/base/auxtel
- name: comcam-gen3-data-temp
  containerPath: /data/lsstdata/base/comcam
  readOnly: true
  server: comcam-archiver.cp.lsst.org
  serverPath: /lsstdata/base/comcam
- name: allsky-data
  containerPath: /data/allsky
  readOnly: true
  server: auxtel-archiver.cp.lsst.org
  serverPath: /data/allsky
- name: scratch-shared
  containerPath: /scratch
  readOnly: false
  server: nfs1.cp.lsst.org
  serverPath: /scratch/rubintv
