namespace: obssys
image:
  repository: ts-dockerhub.lsst.org/scriptqueue
  tag: c0030
  pullPolicy: Always
  nexus3: nexus3-docker
env:
  DAF_BUTLER_REPOSITORY_INDEX: /project/data-repos.yaml
  LSST_DDS_PARTITION_PREFIX: base
  OSPL_INFOFILE: /tmp/ospl-info-mtqueue.log
  OSPL_ERRORFILE: /tmp/ospl-error-mtqueue.log
  RUN_ARG: 1 --state enabled
shmemDir: /run/ospl
osplVersion: V6.10.4
butlerSecret:
  containerPath: &bS-cP /home/saluser/.lsst
  dbUser: oods
secretPermFixer:
- name: butler-secret
  containerPath: *bS-cP
nfsMountpoint:
- name: auxtel-gen3-butler
  containerPath: /repo/LATISS
  readOnly: false
  server: auxtel-archiver.ls.lsst.org
  serverPath: /repo/LATISS
- name: auxtel-gen3-oods
  containerPath: /data/lsstdata/BTS/auxtel
  readOnly: true
  server: auxtel-archiver.ls.lsst.org
  serverPath: /lsstdata/BTS/auxtel
- name: project-shared
  containerPath: /project
  readOnly: false
  server: nfs-project.ls.lsst.org
  serverPath: /project
