namespace: auxtel
image:
  repository: ts-dockerhub.lsst.org/headerservice
  tag: ts-v3.1.12_c0030
  pullPolicy: Always
  nexus3: nexus3-docker
env:
  LSST_DDS_PARTITION_PREFIX: tucson
  LSST_DDS_RESPONSIVENESS_TIMEOUT: 15s
  URL_SPEC: --lfa_mode s3 --s3instance tuc
  S3_ENDPOINT_URL: https://s3.tu.lsst.org
  TSTAND_HEADERSERVICE: TUCSON
  CAMERA: at
  OSPL_INFOFILE: /tmp/ospl-info-atheaderservice.log
  OSPL_ERRORFILE: /tmp/ospl-error-atheaderservice.log
envSecrets:
- name: AWS_ACCESS_KEY_ID
  secretName: lfa
  secretKey: aws-access-key-id
- name: AWS_SECRET_ACCESS_KEY
  secretName: lfa
  secretKey: aws-secret-access-key
- name: MYS3_ACCESS_KEY
  secretName: lfa
  secretKey: aws-access-key-id
- name: MYS3_SECRET_KEY
  secretName: lfa
  secretKey: aws-secret-access-key
shmemDir: /run/ospl
osplVersion: V6.10.4
