namespace: maintel
image:
  repository: ts-dockerhub.lsst.org/mtrotator
  tag: c0030
  pullPolicy: Always
  nexus3: nexus3-docker
env:
  LSST_DDS_PARTITION_PREFIX: tucson
  LSST_SITE: tucson
  OSPL_INFOFILE: /tmp/ospl-info-mtrotator.log
  OSPL_ERRORFILE: /tmp/ospl-error-mtrotator.log
  RUN_ARG: --simulate
shmemDir: /run/ospl
osplVersion: V6.10.4
